### PR TITLE
Intmax

### PR DESCRIPTION
**Pull request by haypo**
Add support for C intmax_t type:

* Add new conversions functions for PyLong:

    * PyLong_FromIntMax()
    * PyLong_FromUIntMax()
    * PyLong_AsIntMax()
    * PyLong_AsIntMaxAndOverflow()
    * PyLong_AsUIntMax()

* getargs: add 'm' format
* New _testcapi constants: INTMAX_MAX, INTMAX_MIN, UINTMAX_MAX, SIZEOF_INTMAX_T
* Add _testcapi.getargs_m() and _testcapi.test_long_intmax_api()
* PyLong_FromVoidPtr() uses PyLong_FromUIntMax()
* Use intmax_t in various modules

array, struct, ctypes and memoryview are not modified yet to support intmax_t.

### CODE REVIEW

**Comment by haypo** [comment]
I know that CPython doesn't use GitHub yet, but I created a pull request to ease the review of this large change.

Related CPython issue: http://bugs.python.org/issue17870

**Comment by eliben** [comment]
OOC, how does it make it easier to review? Github's code review is pretty bare-bones compared to the Rietvield instance CPython uses (IMHO)

**Comment by haypo** [comment]
2016-11-25 14:45 GMT+01:00 Eli Bendersky <notifications@github.com>:
> OOC, how does it make it easier to review? Github's code review is pretty bare-bones compared to the Rietvield instance CPython uses (IMHO)

You can review commits individually.

**Comment by brettcannon** [comment]
Closing this to make sure I didn't miss notifying anyone about the migration.

**Pull request closed without merging**
